geek-fun/dockit

components.d.ts
package-lock.json
package.json
src/App.vue
src/components/VersionDetect.vue
src/electron/preload.ts
src/lang/enUS.ts
src/lang/zhCN.ts
src/store/appStore.ts
src/views/connect/components/connect-dialog.vue
src/vite-env.d.ts
tsconfig.json

feat: auto detect if there is new version avialable

---

components.d.ts
package-lock.json
package.json
src/electron/chatBotApi.ts
src/electron/preload.ts
src/lang/enUS.ts
src/lang/zhCN.ts
src/store/appStore.ts
src/store/chatStore.ts
src/views/editor/index.vue
src/views/setting/components/aigc.vue
src/vite-env.d.ts

feat: enable support for add http proxy for openai 
able to add config for Openai to send requests through the proxy
Refs: #52

feat: enable support for add http proxy for openai #52

---

components.d.ts
src/common/customError.ts
src/electron/preload.ts
src/electron/storeApi.ts
src/lang/zhCN.ts
src/layout/components/chatbot-box.vue
src/layout/components/tool-bar-right.vue
src/store/chatStore.ts

feat: add notification when user first use ai box to indicate user to config the keys first
Refs: #55

feat: notifer to config api keys first

---

components.d.ts
src/lang/enUS.ts
src/lang/zhCN.ts
src/store/connectionStore.ts
src/views/manage/components/cluster-state.vue
src/views/manage/components/node-state.vue

feat: add Manage panel -nodes
- list nodes
- show nodes info
- nodes  statistic metrics
Refs: #17

feat: add Manage panel -nodes

---

components.d.ts
src/assets/styles/theme.scss
src/common/index.ts
src/common/valueConversion.ts
src/lang/enUS.ts
src/lang/zhCN.ts
src/store/clusterManageStore.ts
src/store/connectionStore.ts
src/store/index.ts
src/views/connect/index.vue
src/views/manage/components/alias-dialog.vue
src/views/manage/components/index-dialog.vue
src/views/manage/components/index-manage.vue
src/views/manage/components/shared-manage.vue
src/views/manage/components/template-dialog.vue
src/views/manage/index.vue

feat: add Manage panel -indices
Refs: #17

feat: add Manage panel -indices

---

package-lock.json
src/common/monaco/completion.ts
src/common/monaco/index.ts
src/common/monaco/lexerRules.ts
src/common/monaco/type.ts
src/views/editor/display-editor.vue
src/views/editor/index.vue

feat: path highlight and autocompletion
obsolete now.
Refs: #57

feat: path highlight and autocompletion

---

package-lock.json
package.json
src/common/monaco/completion.ts
src/common/monaco/index.ts
src/common/monaco/lexerRules.ts
src/common/monaco/referDoc.ts
src/common/monaco/tokenlizer.ts
src/views/editor/index.vue
src/views/manage/components/index-manage.vue

feat: enable JSON5 support
- json5 highlight
- json5 covert to JSON when requesting  the server
- json5 format
Refs: #57 #42

feat: json5  as QueryDSL format

---

src/common/monaco/completion.ts
src/common/monaco/keywords.ts
src/common/monaco/lexerRules.ts
src/views/editor/index.vue

feat: render/highlight error syntax
with json5 enabled, to highlight invalid tokens with different colors to improve user experience
Refs: #57 #42

feat: render/highlight error syntax

---

package-lock.json
package.json
src/common/index.ts
src/common/monaco/tokenlizer.ts
src/common/requestUtil.ts
src/datasources/fetchApi.ts
src/lang/enUS.ts
src/lang/zhCN.ts
src/store/connectionStore.ts
src/views/editor/index.vue

feat: enable support for copy command as curl
user can copy the es query as a curl command to action it in the terminal
Refs: #104

feat: enable support for copy command as curl

---

.github/workflows/release.yml
package-lock.json
package.json
src/common/requestUtil.ts
src/datasources/fetchApi.ts
src/store/connectionStore.ts
src/views/editor/index.vue

fix: bulk action with index should pass index to the request url
Refs: #114

fix: bulk action with index

---

src/common/monaco/lexerRules.ts

[feat|fix|refactor: summary title of the PR](fix: should able to support query system indices start with .)
Refs: #120

fix: should able to support query system indices start with .

---

components.d.ts
src/datasources/fetchApi.ts
src/lang/enUS.ts
src/lang/zhCN.ts
src/store/connectionStore.ts
src/views/connect/components/collection-selector.vue
src/views/connect/components/connect-dialog.vue
src/views/manage/components/index-manage.vue
src/views/manage/components/node-state.vue
src/views/manage/components/shared-manage.vue
src/views/manage/index.vue

fix: show error message when user meet 403 error back from server
Refs: #119

fix: show error message when user meet 403 error back from server

---

src/views/file/components/context-menu.vue
src/views/file/components/file-list.vue

fix: hover issue

---

src/lang/enUS.ts
src/lang/zhCN.ts
src/views/file/components/file-list.vue
src/views/file/components/new-file-dialog.vue
src/views/file/components/tool-bar.vue

feat: implement file/folder rename
Refs: #16

feat: implement file/folder rename

---

src/assets/styles/theme.scss
src/common/pureObject.ts
src/views/connect/components/connect-dialog.vue
src/views/file/components/file-list.vue
src/views/file/components/new-file-dialog.vue
src/views/file/components/tool-bar.vue
src/views/login/index.vue
src/views/manage/components/alias-dialog.vue
src/views/manage/components/index-dialog.vue
src/views/manage/components/switch-alias-dialog.vue
src/views/manage/components/template-dialog.vue
src/views/setting/components/aigc.vue

feat: disable input autocompletion and ui improvement
- disable autocapitalize autocompletion
- setup secondary background
- several ui improvement
Refs: #16

feat: disable input autocompletion and ui improvement

---

src/views/editor/index.vue

feat: improve ui height to reduce the shaking issue
Refs: #123

feat: improve ui height to reduce the shaking issue

---

components.d.ts
src/components/tool-bar.vue
src/layout/components/tool-bar-right.vue
src/views/connect/components/connect-list.vue
src/views/connect/index.vue

feat: enable long connection list scrollable
Refs: #142

feat: enable long connection list scrollable

---

.eslintrc.cjs
package-lock.json
src/assets/styles/theme.scss
src/components/tool-bar.vue
src/store/clusterManageStore.ts
src/views/connect/components/connect-list.vue
src/views/connect/components/es-connect-dialog.vue
src/views/connect/index.vue
src/views/editor/index.vue
src/views/manage/components/node-state.vue
src/views/manage/components/shared-manage.vue
src/views/manage/index.vue

chore: chore improves and bug fix
Refs: #142

chore: chore improves and bug fix

---

package-lock.json

fix: win install

---

src-tauri/src/main.rs
src/datasources/fetchApi.ts
src/store/connectionStore.ts
src/views/editor/display-editor.vue
src/views/editor/index.vue

feat: enable support to show text response
Refs: #167

feat: enable support to show text response

---

src/components/tool-bar.vue
src/store/clusterManageStore.ts
src/views/manage/components/index-manage.vue
src/views/manage/index.vue

fix: Fix the manage tab not refreshing data when a new connection is selected
Refs: #182

fix: fix the manage tab not refreshing data when a new connection is selected

---

src/datasources/esApi.ts
src/store/clusterManageStore.ts
src/views/manage/components/template-dialog.vue

feat: hide system components when switch enabled
Refs: #182

feat: hide system components when switch enabled

---

src/views/manage/components/index-manage.vue
src/views/manage/components/shard-manage.vue

refactor: use fullscreen for table
Refs: #185

refactor: use fullscreen for table

---

src/views/manage/components/cluster-state.vue
src/views/manage/components/index-manage.vue
src/views/manage/components/shard-manage.vue

fix: table ui issues
Refs: #185

fix: table ui issues

---

package-lock.json
package.json
src-tauri/src/dynamo/query_table.rs
src-tauri/src/dynamo/scan_table.rs
src/datasources/dynamoApi.ts
src/store/dbDataStore.ts
src/store/index.ts
src/views/editor/dynamo-editor/components/ui-editor.vue

feat: implement dynamodb pagination
Refs: #142

feat: implement dynamodb pagination
